export const HOMEROUTER = '/'
export const CHATROUTER = '/chat'
export const PROPERTYROUTER = '/property'
export const CONTRACTROUTER = '/contract'
export const  AGREEMENTROUTER= '/agreement'
export const  LOGINROUTER= '/login'
export const  REGISTERROUTER= '/register'
export const  PROFILEROUTER= '/profile'